default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# test:
#   <<: *default
#   host: "<%= ENV['TEST_DB_HOST'] %>"
#   database: "<%= ENV['TEST_DB_NAME'] %>"
#   username: "<%= ENV['TEST_DB_USERNAME'] %>"
#   password: "<%= ENV['TEST_DB_PASSWORD'] %>"
#   pool: 1 # to prevent multiple connections being made, unable to see outer open transaction's data.

development:
  <<: *default
  host: "<%= ENV['DEVELOPMENT_DB_HOST'] %>"
  database: "<%= ENV['DEVELOPMENT_DB_NAME'] %>"
  username: "<%= ENV['DEVELOPMENT_DB_USERNAME'] %>"
  password: "<%= ENV['DEVELOPMENT_DB_PASSWORD'] %>"

production:
  <<: *default
  database: Instabug_Task_production
  username: Instabug_Task
  password: <%= ENV["INSTABUG_TASK_DATABASE_PASSWORD"] %>
